# Generated by Django 4.2.6 on 2023-11-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='код верификации'),
        ),
    ]
