# Generated by Django 4.2.6 on 2023-11-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verify_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verify_code',
            new_name='verification_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='верифицирован'),
        ),
    ]
