# Generated by Django 4.2.6 on 2023-10-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SlugField(max_length=150, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(max_length=150, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='names/', verbose_name='изображение(превью)')),
                ('purchase_price', models.IntegerField(verbose_name='цена за покупку')),
                ('date_creation', models.DateField(max_length=150, verbose_name='дата создания')),
                ('date_last_mod', models.DateField(max_length=150, verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
    ]
