# Generated by Django 4.2.6 on 2023-10-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='num_of_version',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='номер текущей версии'),
        ),
    ]
