# Generated by Django 4.2.6 on 2023-11-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
