# Generated by Django 4.2.6 on 2023-11-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
